tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

# brew "awscli"
brew "nodenv"
brew "starship"

cask "1password"
cask "alfred"
cask "appcleaner"
cask "deepl"
cask "docker"
cask "dotnet-sdk"
cask "font-fira-code-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "karabiner-elements"
cask "rectangle"
cask "rider"
cask "skitch"
cask "tableplus"
cask "teamviewer"
cask "visual-studio-code"
cask "zoom"

mas "LINE", id: 539883307
mas "Velja", id: 1607635845
